# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.apps.catalogue.reviews.utils
import oscar.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20170429_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-delta_votes', 'id'], 'verbose_name': '策略评论', 'verbose_name_plural': '策略评论'},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='homepage',
            field=models.URLField(blank=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='score',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '需求修改'), (1, '批准'), (2, '拒绝')], default=oscar.apps.catalogue.reviews.utils.get_default_review_status, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=255, validators=[oscar.core.validators.non_whitespace], verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='total_votes',
            field=models.IntegerField(default=0, verbose_name='所有的投票'),
        ),
    ]
