# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='商品名称')),
                ('price', models.FloatField(default=0, verbose_name='购买价格')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('exchanges', models.TextField(default='', verbose_name='支持交易所列表')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': 'quant_policy',
                'db_table': 'quant_policy',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='QuantPolicyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=20)),
                ('policy_start_time', models.DateTimeField()),
                ('policy_end_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('policy_name', models.CharField(default='', max_length=200)),
                ('policy_url_add', models.CharField(default='', max_length=50)),
                ('policy_url_list', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'quant_policy_order',
                'db_table': 'quant_policy_order',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
