# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_email_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractDepositRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payaccount', models.CharField(default='', max_length=255, verbose_name='来源账号')),
                ('memo', models.CharField(default='', max_length=255, verbose_name='备注')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='充值数量')),
                ('txid', models.CharField(default='', max_length=255, verbose_name='交易ID')),
                ('source', models.CharField(default='', max_length=255, verbose_name='币种')),
                ('block_time', models.DateTimeField(verbose_name='区块时间')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='rmb价格')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'ordering': ('-createtime',),
                'abstract': False,
            },
        ),
    ]
